# Generated by Django 3.2.7 on 2021-09-22 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('starthour', models.TimeField(verbose_name='start hour ')),
                ('endhour', models.TimeField(verbose_name='end hour ')),
                ('title', models.TextField(verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('equipment', models.TextField(verbose_name='equipment')),
                ('state_befor', models.TextField(blank=True, null=True, verbose_name='state befor ')),
                ('state_after', models.TextField(verbose_name='state after ')),
                ('device_used', models.TextField(blank=True, null=True, verbose_name='Device Used')),
                ('type_di', models.CharField(choices=[('CHEF_DEP', 'Par le Chef departement Informatique'), ('CHEF_SRV', 'Par le Chef service IR&SI'), ('DI', 'Par DI'), ('MAIL', 'Par Mail'), ('TR_INTR', 'Travaux Internes à La Structure')], default='TR_INTR', max_length=20, verbose_name='Type DI')),
                ('n_di', models.TextField(blank=True, null=True, verbose_name='N° DI')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
